### ISSUE TITLE
Split up client & server npm dependencies

### ISSUE THREAD

**Issue by david-martin** [integr8ly/tutorial-web-app#10]
Currently server & client (react) dependencies are all defined in the 1 package.json.
This could lead to unnecessary dependencies being included in the client or server.

It also limits the version of dependencies to a single version between client & server, if they use the same dependency.

**Comment by dlabaj** [comment]
@david-martin Are we still plaining on doing this?

**Comment by david-martin** [comment]
@dlabaj It makes sense to me to do it.
What do you think?

**Comment by dlabaj** [comment]
@david-martin Yes makes sense to me as well.  You think this is something we should get in before the next release?

**Comment by david-martin** [comment]
I think sooner rather than later would be good on this one.
Feel free to take it on

**Comment by tiffanynolan** [comment]
Moved to JIRA: https://issues.jboss.org/browse/INTLY-336
