### ISSUE TITLE
Remove travis

### ISSUE THREAD

**Issue by pb82** [integr8ly/tutorial-web-app#142]
We're currently using Circle.ci (building and pushing images) and Travis (running the tests per PR). Circle.ci can do the same as Travis (there's an option to run tests for every PR). I think it would make sense to enable that and get rid of Travis.

**Comment by dlabaj** [comment]
@pb82 Did you want to take this issue?

**Comment by pb82** [comment]
@dlabaj yes, i'm happy to take this.

**Comment by pb82** [comment]
Travis is gone now. Pull requests will trigger Circle.ci to run the unit tests. Status can be seen directly in Github. The docker images are only built when the PR is merged.
