### ISSUE TITLE
Task level breadcrumb

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#155]
As a user, I'd like to see what task I'm performing while performing a walkthrough

https://i.imgur.com/M10daEb.png

In this example, I'm 'Creating Connectors', but that's not rendered

**Comment by mindreeper2420** [comment]
I believe the designs have the title of the task in the content area (which is missing in the screenshot). Would that remedy this issue?

Sounds like this and issue https://github.com/integr8ly/tutorial-web-app/issues/50 could be connected.

**Comment by dlabaj** [comment]
@finp Is this the same as issue #50 ?

**Comment by finp** [comment]
there are two methods to get material into webapp
1. parsing adoc for step text, #50 is related to that
2. Task headings from json, I believe this issue relates to that
so the issue is that the following isn't rendered afaik https://github.com/integr8ly/tutorial-web-app/blob/97719ea17a7fa88ddbc880e0e391f88490ce647b/public/steelthreads/json/en/thread-1.json#L16

**Comment by tiffanynolan** [comment]
@finp Should we move this item to JIRA for further investigation?

**Comment by finp** [comment]
@tiffanynolan late reply ;) yes

**Comment by catrobson** [comment]
@finp thanks for the suggestion.  At this point in time, we're not going to add this enhancement due to other priorities.  I'm going to close this issue, and we can create a new one in the future if this becomes a high priority through usage.
