### ISSUE TITLE
Username / email in upper right corner missing

### ISSUE THREAD

**Issue by dlabaj** [integr8ly/tutorial-web-app#156]
Username / email is hard coded to developer in drop down in upper right corner of the masthead.  The current email or username should be displayed in the masthead instead.

<img width="267" alt="screen shot 2018-10-17 at 3 14 27 pm" src="https://user-images.githubusercontent.com/6126356/47110633-6085ca00-d21f-11e8-8518-8c9a630ede84.png">

**Comment by JarrydTrokis** [comment]
I'm on it

**Comment by JarrydTrokis** [comment]
It looks like you're using the spread operator to overwrite the state.

`  if (reset && prop) {
    obj[prop] = {
      ...state[prop],
      ...initialState[prop],
      ...data
    };
  } else if (reset && !prop) {
    obj = {
      ...state,
      ...initialState,
      ...data
    };
  } else if (prop) {
    obj[prop] = {
      ...state[prop],
      ...data
    };
  } else {
    obj = {
      ...state,
      ...data
    };
  }`

I would seem that you're overwriting the state with the initial state.
