### ISSUE TITLE
Create a PR Template

### ISSUE THREAD

**Issue by mindreeper2420** [integr8ly/tutorial-web-app#164]
This issue is to track the creation of a PR template that satisfies the requirements of the different levels of code introduced into the webapp (middle, UI), as well as introduce a verification step for UXD.

Starting thoughts:
- all tests must pass (JS and CSS)
- if the code touches the UI, it must be reviewed by UXD
- any content changes must be reviewed by Docs, or have a link to a previous document stating the desired changes
- the webapp must continue to operate using mock data

Currently, there is no defined standard for who should review what type of work, and what each code change must verify before merging. The hope is that a template such as this can assist with creating a smoother process.

**Comment by mindreeper2420** [comment]
**First Draft:**

Description of Pull Request:

Changes:
- 1
- 2
- 3

Link to Reference Doc (if applicable):
[insert link here]

Screenshot of Implementation (if applicable):
![screen shot 2018-10-19 at 9 38 47 am](https://user-images.githubusercontent.com/4032718/47221599-cdfe3b80-d382-11e8-9c24-a7706dab865e.png)

Checklist:
[ ] All Test Pass (run `yarn run test` to verify)
[ ] Content is complete
[ ] Design is approved
[ ] Works deployed on OpenShift?
[ ] Works in mock mode?

**Comment by catrobson** [comment]
@mindreeper2420 should we also link to the github issue or trello card that originated this work?

The checklist is a bit confusing - are you expecting the person creating the issue to check those off or those watching the repo responsible for each item to check them off?

**Comment by mindreeper2420** [comment]
@catrobson this actually originated from a discussion been Don, Mark, and myself. I also spoke with Brian on trying to come up with a way to have design review UI changes, before they actually make it into production.

The checklist is something that the creator of the PR should be able to check off - each item verifies (or should help to verify) that the PR is not being done without any previous knowledge. This is something that PatternFly does, to ensure that the work behind the PR going into Core has already been vetted by the necessary parties.

**Comment by davidffrench** [comment]
I hadn't realised this issue existed before submitting my own suggestion here - https://github.com/integr8ly/tutorial-web-app/pull/212

## Motivation
Add references to relevant tickets or a short description about what motivated you do it. (E.g Trello Card AND/OR GitHub ISSUE: https://github.com/integr8ly/tutorial-web-app/issues) 

## What
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)

## Why
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)

## How
Add an short answer for: How it was done? (E.g By removing this feature from ... OR By removing just the button but not its implementation ... ) 

## Verification Steps
Add detailed steps required to check this change. Following an example.
 
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.

## Checklist:
- [ ] All Test Pass (run yarn run test to verify)
- [ ] Content is complete
- [ ] Design is approved
- [ ] Works deployed on OpenShift?
- [ ] Works in mock mode?
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes
PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the users.
