### ISSUE TITLE
When I click 'Next', webapp crashes

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#175]
In WT1A, the first task appears and renders correctly. (http://localhost:3006/tutorial/1A/task/0)
However, after verification, and clicking next I get 
TypeError: Cannot set property '0' of undefined

As a workaround, I can set the URL to http://localhost:3006/tutorial/1A/task/1 and the next task renders correctly

**Comment by mfrances17** [comment]
I can't reproduce this issue - however, I made some changes to WT1A and task.js at the end of last week that most likely fixed it. Please retest using the latest build and if it still fails on your end, reopen this issue as necessary. Thanks!
