### ISSUE TITLE
Request: Lock Dependency Versions

### ISSUE THREAD

**Issue by mindreeper2420** [integr8ly/tutorial-web-app#178]
As the web app progresses I would like to see the dependencies listed in the `package.json` file be locked down to specific versions, rather than using the `^`. The `yarn.lock` file should not have to change unless there is a specific need for an introduction of a new dependency, or a vital version update.

**Comment by mindreeper2420** [comment]
@dlabaj @mfrances17 @aidenkeating @david-martin - Thoughts on taking this step? IMO, it would introduce a level of certainty and help to eliminate and variations in builds and local environments.

**Comment by mfrances17** [comment]
Yeah, I agree that this is the right thing to do, @mindreeper2420.

**Comment by david-martin** [comment]
+1

**Comment by mindreeper2420** [comment]
This is fixed by PR #192.
