### ISSUE TITLE
Add HTML ids to important HTML components

### ISSUE THREAD

**Issue by tremes** [integr8ly/tutorial-web-app#189]
It would be helpful to have HTML ids in components like "Get started" walkthrough link, buttons in the walkthrough etc. This would make UI testing easier. 

I'd do it myself, but some ids need to be generated dynamically and I don't know React and PatternFly much.

**Comment by mfrances17** [comment]
Agree, this is a great point. We should plan to do a sweep to add Ids for existing components in an upcoming sprint, and then make it a requirement for new components to have Ids going forward.

**Comment by dlabaj** [comment]
There's a utility in PF4 to help with this.  Should do this as part of the PF4 effort.

**Comment by tiffanynolan** [comment]
I added this as a task in our PatternFly 4 Adoption epic: https://issues.jboss.org/browse/INTLY-337. Additional work will be tracked in that issue.
