### ISSUE TITLE
Improve Accessibility of Webapp

### ISSUE THREAD

**Issue by mindreeper2420** [integr8ly/tutorial-web-app#190]
The accessibility of the webapp needs to be improved, in order to meet the proper guidelines, as set by the [Web Content Accessibility Guidelines 2.1](url
https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa).

PatternFly 4 provides a guide for reaching this goal, as well as various informational boxes at the end of components. [PatternFly 4 Accessibility Guide](https://pf-next.com/accessibility-guide)

**Comment by tiffanynolan** [comment]
Moved to JIRA under the PF4 Epic: https://issues.jboss.org/browse/INTLY-338. Work will be tracked in that issue going forward.
