### ISSUE TITLE
General - Clicking "Red Hat Solution Explorer" shows loading screen

### ISSUE THREAD

**Issue by davidffrench** [integr8ly/tutorial-web-app#205]
## Expected Behavior
After all initial setup is complete, I would expect clicking the home button "Red Hat Solution Explorer" to bring me to only the dashboard.

## Actual Behavior
Clicking "Red Hat Solution Explorer" briefly shows the loading screen before showing the dashboard.

![2018-11-08_10-49-18](https://user-images.githubusercontent.com/1596014/48194625-6f0a6180-e345-11e8-9b3d-a499caddebd5.gif)

## Steps to Reproduce the Problem
  1. Click "Red Hat Solution Explorer"
  1. The loading screen is shown briefly

## Specifications
  - Browser: Chrome

**Comment by camilamacedo86** [comment]
It shows be the same of : https://github.com/integr8ly/tutorial-web-app/issues/230

**Comment by tiffanynolan** [comment]
Issue migrated to JIRA for prioritization in the backlog. https://issues.jboss.org/browse/INTLY-380
