### ISSUE TITLE
Walkthrough - No margins on the walkthroughs text or button

### ISSUE THREAD

**Issue by davidffrench** [integr8ly/tutorial-web-app#206]
## Expected Behavior
Margins on the walkthrough text and "Get Started" button

## Actual Behavior
It does not look like any margins are present

![2018-11-08_12-11-20](https://user-images.githubusercontent.com/1596014/48198061-877f7980-e34f-11e8-9e8f-4998b57029ba.png)

## Steps to Reproduce the Problem
  1. Click on any of the walkthroughs

## Specifications
  - Browser: Chrome

**Comment by mindreeper2420** [comment]
Fixed with PR #229
