### ISSUE TITLE
Launcher text runs out of Runtime model

### ISSUE THREAD

**Issue by austincunningham** [integr8ly/tutorial-web-app#207]
# Issue
In Launcher text runs out of Runtime model

![launcher](https://user-images.githubusercontent.com/16667688/48198855-26a57080-e352-11e8-8f64-6a1e6ffa02ea.png)

>**NOTE** used tag release-1.0.1 of the installer

**Comment by david-martin** [comment]
@gastaldi is this something you're aware of or maybe have fixed in a later version than we're using?

**Comment by david-martin** [comment]
Thanks @gastaldi.

@austincunningham closing this. The fix will be picked up when we change to later version of Launcher
