### ISSUE TITLE
No message to tell what the issue is if github oauth not set in Launcher

### ISSUE THREAD

**Issue by austincunningham** [integr8ly/tutorial-web-app#208]
# Issue 
Creating github oAuth link,
![git-autorisation](https://user-images.githubusercontent.com/16667688/48199141-14780200-e353-11e8-8cee-3b5ba3b0b0c3.gif)

Only happens if **github_client_id** and **git_client_secret** not set

# Workaround 
Run the installer with the keys
```
ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=<your_client-id> -e github_client_secret=<your_client_secret>
```
>**NOTE** used tag release-1.0.1 of the installer

**Comment by davidffrench** [comment]
After talking to Aiden, an alternative workaround is the following.

1. Login to OpenShift as admin@example.com
2. Open the launcher project
3. Follow the link to the Keycloak UI - secure-launcher-sso-launcher.apps<rest of url> and login as admin
4. Click on Identity Providers and add a new GitHub identity provider
5. Open GiHub and go to settings > developer settings and create a new OAuth app
6. Open the uri from keycloak to the "callback URL" field in GitHub. Give the OAuth app app name and url in GitHub and click create.
7. Copy the Client ID and Client Secret back to keycloak.
8. Other fields to change in keycloak
- Default Scopes: admin:repo_hook,read:org,public_repo
- Store Tokens: On
- Store Tokens Readable: On
- Enabled: On
- Trust Email: On
9. Click Save
10. Go back to the launcher and retry the "Log in and authorise account"

**Comment by david-martin** [comment]
Closing for 3 reasons:

* Thanks @davidffrench for giving workaround instructions
* These instructions are now included (with screenshots) when an internal cluster is created (PDS)
* We'll likely setup Launcher to use Gitea instead of Github for integreatly clusters in the near future.
