### ISSUE TITLE
Typo on Upload OpenAPI Specification page

### ISSUE THREAD

**Issue by craicoverflow** [integr8ly/tutorial-web-app#209]
In `Home > Customizations > API Client Connector` on the *Upload OpenAPI Specification* section there is a typo:

> Upload the OpenAPI 2.0 file for your custom API client *ocnnector* ...

This should be *connector*.

![integreatly issue](https://user-images.githubusercontent.com/11743717/48199463-f78ffe80-e353-11e8-8207-2eb6f83e5fdf.png)

**Comment by david-martin** [comment]
Looks to be fixed here https://github.com/syndesisio/syndesis/commit/c31525d16089644ff836a2d87713cd0139f4ee9d#diff-1e67c5b02b5dbd41a128f26070714800R45
Will pick this up when we upgrade to later version of Fuse Online
