### ISSUE TITLE
Homepage - Log out

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#213]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

Homepage - s/b “Log out” (two words) on the user’s menu
Homepage - “Log out” needs  to be logout user.

**Comment by david-martin** [comment]
@camilamacedo86 Is there a PR related to this? Or is this still a valid issue?

**Comment by tiffanynolan** [comment]
@mfrances17 Can you look into this and make the changes if still applicable. I'm not sure this one is worth migrating over to JIRA if it's a quick fix.

**Comment by mfrances17** [comment]
Hi... I think there is a decision to be made, if we want to change 'Logout' to 'Log out', or if we want to change 'Logout' to 'Logout <user>'. These were two separately filed issues that I combined into one GitHub issue.

The former would match OpenShift, the latter I feel is redundant because the drop-down menu itself is named according to the user (so for example, it would be admin@example.com > Log out admin@example.com).

Either would be a relatively quick fix, and we don't have to port this over to JIRA.
