### ISSUE TITLE
Clicking an application brings you to login

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#214]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

When I click on any application, I’m brought to the login. I assume that means SSO isn’t implemented yet?

**Comment by david-martin** [comment]
> SSO isn’t implemented yet

Correct. Full SSO is not implemented, but is something on the roadmap for integreatly clusters in general.
Closing as this isn't something that can be rectified in the webapp
