### ISSUE TITLE
Spacing issues around walkthrough header

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#216]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

Spacing around walkthrough header is too small, should be the same spacing as headers on the walkthrough process pages:

![image](https://user-images.githubusercontent.com/39063664/48211425-72065180-e347-11e8-981e-91f719ce237e.png)

**Comment by mindreeper2420** [comment]
Fixed by PR #229
