### ISSUE TITLE
Move walkthrough diagram to right-hand side

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#217]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

The diagram on the walkthrough intro needs to move to the right-hand side, gray column.

**Comment by tiffanynolan** [comment]
Work on this issue will continue in JIRA. https://issues.jboss.org/browse/INTLY-368
