### ISSUE TITLE
Graphics load times seem long

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#221]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

Loading time on success state is a bit slow - is there any way to speed this up?

Look at optimizing the background images so they load quicker (maybe just try progressive load, at the very least)

**Comment by mindreeper2420** [comment]
Currently, all background images are also given a default color (resembling the main color of the image), in order to provide something other than a white background while the image loads.

To test the speed at which the images appear, you can set the Chrome Developer Tools to run over a 3g network.

**Comment by mindreeper2420** [comment]
@bdellasc - is this something where you want to just supply smaller logos or compress them more?

**Comment by bdellasc** [comment]
I guess some guidance on dimensions would be helpful. I believe I made them larger physical dimensions and higher resolution to render on hi-res screens. Maybe we can do some side-by-side tests to see what would be least visually detrimental to the image quality and give us better loading speeds? I can work with you next week on that.

**Comment by mindreeper2420** [comment]
After talking with Brian, it was determined that images matching the dimensions found here: https://github.com/patternfly/patternfly-next/tree/master/static/assets/images under `pfbg_###.jpg` are needed.

These images would then translate into CSS that would render the different sized images based on media queries, targeting both viewport size, pixel ratio (1x vs 2x), and resolution DPI.

**Comment by bdellasc** [comment]
@mindreeper2420 - I did a first pass on the images, but was unhappy with how the pattern band scaled for some sizes. I'm going to spend some time cleaning them up before I post them for consumption.

**Comment by bdellasc** [comment]
@mindreeper2420 try these out

![congratsbg_576](https://user-images.githubusercontent.com/17882357/48379909-c12fe780-e6a3-11e8-84c8-f2e38df59cb2.jpg)
![congratsbg_576 2x](https://user-images.githubusercontent.com/17882357/48379910-c12fe780-e6a3-11e8-918f-312d48a93dab.jpg)
![congratsbg_768](https://user-images.githubusercontent.com/17882357/48379912-c12fe780-e6a3-11e8-87df-c0c60477ef8d.jpg)
![congratsbg_768 2x](https://user-images.githubusercontent.com/17882357/48379913-c12fe780-e6a3-11e8-9c09-cd6d92fcbc9c.jpg)
![congratsbg_992](https://user-images.githubusercontent.com/17882357/48379914-c12fe780-e6a3-11e8-8c59-526d325205e0.jpg)
![congratsbg_992 2x](https://user-images.githubusercontent.com/17882357/48379915-c12fe780-e6a3-11e8-8e34-20378381045f.jpg)
![congratsbg_1200](https://user-images.githubusercontent.com/17882357/48379916-c12fe780-e6a3-11e8-8d40-ab44470ae194.jpg)
![congratsbg_2000](https://user-images.githubusercontent.com/17882357/48379917-c12fe780-e6a3-11e8-95ae-1f909a72a136.jpg)
![loadingbg_576](https://user-images.githubusercontent.com/17882357/48379918-c12fe780-e6a3-11e8-80eb-5176159abc47.jpg)
![loadingbg_576 2x](https://user-images.githubusercontent.com/17882357/48379919-c12fe780-e6a3-11e8-9e3d-3acd43bd936f.jpg)
![loadingbg_768](https://user-images.githubusercontent.com/17882357/48379921-c1c87e00-e6a3-11e8-89c8-ce810ecaefc9.jpg)
![loadingbg_768 2x](https://user-images.githubusercontent.com/17882357/48379922-c1c87e00-e6a3-11e8-89ff-e2d739369d5a.jpg)
![loadingbg_992](https://user-images.githubusercontent.com/17882357/48379923-c1c87e00-e6a3-11e8-9c28-00ca5ed2dc7b.jpg)
![loadingbg_992 2x](https://user-images.githubusercontent.com/17882357/48379924-c1c87e00-e6a3-11e8-991c-fad9795cceea.jpg)
![loadingbg_1200](https://user-images.githubusercontent.com/17882357/48379925-c1c87e00-e6a3-11e8-8963-dee466991cb0.jpg)
![loadingbg_2000](https://user-images.githubusercontent.com/17882357/48379926-c2611480-e6a3-11e8-9a07-23302aa32857.jpg)

**Comment by mindreeper2420** [comment]
Completed with the merge of the referenced PR.
