### ISSUE TITLE
Spacing should be consistent between walkthrough headers and resources

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#222]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

The spacing between the top of the header and 2.1 Creating an API Connector and the spacing between the top of the header and walkthrough resources should be the same and should be aligned.

**Comment by mindreeper2420** [comment]
@mfrances17 do you know if there is an image of this defect available?

**Comment by mfrances17** [comment]
The original person who added the comment didn't provide one, but I captured what I think they probably meant. Notice the difference in space above the '2.1 Creating an API Connector' header vs. the space above the 'Walkthrough Resources' header on the right.

![space-issues](https://user-images.githubusercontent.com/39063664/48216315-5d7b8680-e352-11e8-8d13-b40bf9b17663.png)

**Comment by mindreeper2420** [comment]
ah, ok. This will be fixed with PR https://github.com/integr8ly/tutorial-web-app/pull/229. I adjusted both alignments to match the mockup.

**Comment by mindreeper2420** [comment]
Fixed with PR #229
