### ISSUE TITLE
Progress not saved when returning to homepage via breadcrumb

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#223]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

Let’s say I’ve completed task 1 of 4. Then I want to go back to the tutorial homepage, so I click on the title in the breadcrumb. I go to the tutorial homepage and I click “get started.” My progress has not been saved. Ideally the web app would record my progress. (I believe this is happening only when I click through the breadcrumb)

**Comment by aidenkeating** [comment]
@mfrances17 I believe this was resolved in https://github.com/integr8ly/tutorial-web-app/pull/367. If it comes up again we can re-open this issue.
