### ISSUE TITLE
Card alignment needs to be improved

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#224]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

The cards should be moved up a millimeter to be aligned with the line under applications. Here it is out of alignment:

![image](https://user-images.githubusercontent.com/39063664/48212105-e988b080-e348-11e8-8e98-8d141a6aa9f2.png)

**Comment by mindreeper2420** [comment]
Fixed by PR #228
