### ISSUE TITLE
Spacing inconsistencies between header and titles

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#225]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

Spacing between header and titles should be consistent across the flow

![image](https://user-images.githubusercontent.com/39063664/48212183-11781400-e349-11e8-9bd1-dd351dcaa3a6.png)

**Comment by mindreeper2420** [comment]
I believe this is related to https://github.com/integr8ly/tutorial-web-app/issues/222?

**Comment by mindreeper2420** [comment]
Fixed with PR #229
