### ISSUE TITLE
Walkthrough - Navigation between walkthrough tasks displays the loading screen

### ISSUE THREAD

**Issue by davidffrench** [integr8ly/tutorial-web-app#230]
## Description
When navigating between walkthrough tasks, the loading screen is displayed. To me this seems unnecessary as the only change is the text for the next walkthrough task. Maybe this is because of the need to retrieve data for the "Copy Input" fields.

## Expected Behavior
No loading screen between walkthrough tasks

## Actual Behavior
Loading screen being displayed between walkthrough steps

## Steps to Reproduce
1. Select Walkthrough
2. Click next

## Specifications
  - Browser: Chrome
  - Browser version: 70.0.3538.77
  - OS: MacOS Mojave

## Additional Notes
![2018-11-08_17-22-53](https://user-images.githubusercontent.com/1596014/48215863-18b81580-e37b-11e8-9eb0-8bc5a77cce8b.gif)

**Comment by camilamacedo86** [comment]
It shows be the same of : https://github.com/integr8ly/tutorial-web-app/issues/205

**Comment by tiffanynolan** [comment]
Migrated over to JIRA backlog for prioritization and further investigation. Work will continue there. https://issues.jboss.org/browse/INTLY-379
