### ISSUE TITLE
Walkthrough - Documentation - Login step duplicated across sections of a task

### ISSUE THREAD

**Issue by davidffrench** [integr8ly/tutorial-web-app#231]
## Description
While on a single task of a walkthrough, the first step of each section asks the user to login to a Red Hat application to perform the steps. For example, task 1 of walkthrough 1 asks the user to login to `Red Hat Fuse Online` for both section 1.1 and 1.2. In my opinion, since the user is already logged in from section 1.1, the step to log in on 1.2 is not necessary. 

## Expected Behavior
Reduce the number of steps by removing duplicate login steps that have already been performed.

## Actual Behavior
Login steps duplicated on walkthrough tasks

## Steps to Reproduce
1. Select the `Integrating event-driven and API-driven applications (AMQ)` walkthrough
2. Click `Get Started`
3. Step 1 from both section 1.1 and 1.2 require the user to log into the Red Hat Fuse Online console.

## Specifications
  - Browser: Chrome
  - Browser version: 70.0.3538.77
  - OS: MacOS Mojave

## Additional Notes
![2018-11-08_17-32-50](https://user-images.githubusercontent.com/1596014/48216349-5ff2d600-e37c-11e8-8092-a6dcab09d965.png)

**Comment by finp** [comment]
@stacymcauliffe We discussed this and decide to leave as-is for now, is that correct?

**Comment by stacymcauliffe** [comment]
We either want to repeat this step consistently at the beginning of each task, or we want to say it only once and assume the user will understand that they are staying in the application. 

For users who go through an entire walkthrough end to end in one sitting, the latter approach is preferable. The risk we take with that approach is the user who stops in the middle of a walkthrough and then comes back to the web app will have no obvious way to log in to their console again. 

The simplest solution IMO is to repeat the log in info at the beginning of each task. We could also spend some time considering a design solution for this story if the team thinks it's very disruptive to repeat that log in step (as a user, I want to be able to return to a walkthrough I've partially completed and get the correct log in information).

**Comment by finp** [comment]
closing, might need to be reopened in the context of reviewing  partially completed walkthroughs
