### ISSUE TITLE
need to make sure integration is running before you can enter fruit

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#237]
Task 2 of Walkthrough 1 (and maybe 1A) ask you to verify step by making sure integration exists before continuing. 
However, you need to make sure the integration is running, 

Fix: Update docs and check 1A for similar error

**Comment by catrobson** [comment]
Also we should note that you need to refresh the CRUD app to see your new fruits (Spring Boot app) since there isn't a real-time refresh on that application. on Task 3 of Walkthrough 1.

**Comment by tiffanynolan** [comment]
@mfrances17 Are there any improvements that can be made in relation to Cat's comments as part of https://issues.jboss.org/browse/INTLY-106?

@finp Should we move this over to JIRA for prioritization in the backlog?

**Comment by tiffanynolan** [comment]
Work will be prioritized in JIRA and continue to be worked on there. https://issues.jboss.org/browse/INTLY-377
