### ISSUE TITLE
Text overlapping loading bar

### ISSUE THREAD

**Issue by catrobson** [integr8ly/tutorial-web-app#238]
Text is overlapping with the loading bar when screens are resized to be smaller.

![image](https://user-images.githubusercontent.com/3739227/48265322-24abe200-e424-11e8-8c5a-063b6b09fdc5.png)

**Comment by mindreeper2420** [comment]
@catrobson do you know what resolution screen you saw this on?

**Comment by catrobson** [comment]
starts happening at different resolutions for different load screens based on the length of the content from what I saw, but this one in particular I was able to replicate at about 1160 x 649 when it starts rolling over the login bar.

Using Chrome.

**Comment by mindreeper2420** [comment]
@catrobson Once webapp-005 is updated with the latest version of master, this can be verified either as fixed or not.

**Comment by mindreeper2420** [comment]
Verified through multiple revisions of master and running different webapp environments that this is fixed.
