### ISSUE TITLE
Misleading URLs when some of the components fails to provision

### ISSUE THREAD

**Issue by tremes** [integr8ly/tutorial-web-app#250]
## Description
When provisioning some of the components fails then the default URLs are used (which now means cluster-lfa3xlh.opentry.me) so in case of some unexpected failure you can end up on completely different cluster.

## Expected Behavior
I think we should display some error or warning to the user instead of silently pretending everything is fine. 

## Steps to Reproduce
1.
2.

## Specifications
  - Browser:
  - Browser version:
  - OS:

**Comment by camilamacedo86** [comment]
Hi @tremes,

Is it something that still valid? If, yes, please could you improve the first comment with step by step how to reproduce this scenario. (e.g https://github.com/integr8ly/tutorial-web-app/issues/205)

**Comment by tremes** [comment]
@camilamacedo86 I think this might be still valid. I would like to try to reproduce it and will add more info if I'm successful.

**Comment by tremes** [comment]
Well so I wasn't able to reproduce this problem. Anyway I think there might be an issue when some of the service instances fails to provision. Then the webapp won't be able to load at all (loading bar will hang forever). This will likely be addressed in https://issues.jboss.org/browse/INTLY-80.

**Comment by aidenkeating** [comment]
@tremes Closing this as we now have a per-service loading screen that shows errors for a service if it fails to provision and gives the users some options.
