### ISSUE TITLE
The Route id for the spring boot crud app has a name that is too long, preventing it from being created (WT1A)

### ISSUE THREAD

**Issue by jasonmadigan** [integr8ly/tutorial-web-app#251]
## Description
The Route id for the spring boot crud app has a name that is too long, preventing it from being created (WT1A)

## Expected Behavior
The route should work

## Actual Behavior
The route is too long, so fails to be created

## Steps to Reproduce
1. Go into WT1A
2. The Spring Boot app route will not work

## Specifications
  - Browser: N/A
  - Browser version: N/A
  - OS: N/A

## Additional Notes
![image](https://user-images.githubusercontent.com/4467/48492634-1eea3e00-e822-11e8-88fe-2ff03a3d5aff.png)
![image 1](https://user-images.githubusercontent.com/4467/48492642-214c9800-e822-11e8-8887-79d082b6bea7.png)

**Comment by jasonmadigan** [comment]
@david-martin @maleck13 @aidenkeating ^

**Comment by aidenkeating** [comment]
@jasonmadigan @david-martin @maleck13 I'll take a look at this today

**Comment by jasonmadigan** [comment]
thanks @aidenkeating

**Comment by david-martin** [comment]
fixed by https://github.com/integr8ly/installation/pull/146
