### ISSUE TITLE
After upgrading to EnMasse 0.24.1 the webapp provision of EnMasse fails

### ISSUE THREAD

**Issue by maleck13** [integr8ly/tutorial-web-app#257]
## Description
We are testing the upgrade of EnMasse to 0.24.1 however they have changed the plan name from unlimited-standard to standard-unlimited. This causes the EnMasse provision to fail

## Expected Behavior
EnMasse should provision
## Actual Behavior
EnMasse doesn't provision

# Solution
change https://github.com/integr8ly/tutorial-web-app/blob/c1aaa89e3518d6744d9c1545810e0904af03a166/src/common/serviceInstanceHelpers.js#L49 to use standard-unlimited

**Comment by david-martin** [comment]
closed by #https://github.com/integr8ly/tutorial-web-app/pull/260
