### ISSUE TITLE
W1A - steps describing EnMasse login seem to change a little bit after EnMasse update

### ISSUE THREAD

**Issue by tremes** [integr8ly/tutorial-web-app#268]
## Description
First step in W1A says:

> Log into EnMasse by selecting the OpenShift button on the log in screen and accepting the permissions request.

But it looks there's no more any OpenShift button 

## Steps to Reproduce
1.
2.

## Specifications
  - Browser:
  - Browser version:
  - OS: 

## Additional Notes
PS.: Add images and/or .gifs to illustrate the issue

**Comment by david-martin** [comment]
Addressed in https://github.com/integr8ly/tutorial-web-app/pull/267

**Comment by camilamacedo86** [comment]
Closing this one since the #267 is merged. Please, @tremes feel free to re-open case the #267 did not attend your expectation here.
