### ISSUE TITLE
AMQ Broker isn't available when user tries to register url

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#274]
## Description
When performing Walkthrough 1, a user can be asked to enter  a value into the broker URL field, but that value may not be rendered in web app, due to AMQ not being ready to provide it

## Expected Behavior
Text similar to following:

Enter the following into the Broker URL field: tcp://broker-amq-tcp.admin-example-com-walkthrough-projects.svc:61616

## Actual Behavior

tcp://{amq-broker-url}:61616

## Notes

reported at Waterford Workshop

**Comment by camilamacedo86** [comment]
Hi @finp,

Is it something that still valid/required? If yes, please, could you try to do the first comment as [here](https://github.com/integr8ly/tutorial-web-app/blob/master/.github/ISSUE_TEMPLATE.md) and describe the steps required to reproduce and check this issue?  ( e.g #205 )

**Comment by finp** [comment]
@aidenkeating  is this something you've got covered?

**Comment by aidenkeating** [comment]
@finp Just to confirm, the bug is that it's not available initially, but eventually it does become available. Is that correct?

If so, we don't have a solution implemented yet, I don't think it's planned for the upcoming sprint either.

**Comment by finp** [comment]
@aidenkeating  yes, you describe it perfectly. 
We could initialize the attribute with something like:
`:amq-broker-url: Service is still being provisioned- please wait`

**Comment by catrobson** [comment]
@aidenkeating @finp I believe this issue has been removed due to our move to using Fuse Online.  If so, can we close this issue?

**Comment by finp** [comment]
out of date
