### ISSUE TITLE
Support single step tasks

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#287]
## Description

currently, single step tasks require duplication of text.
If you step the task heading, the verification doesnt' appear 

## Desired behaviour

= Walkthrough

== Task1  title

. procedure
. process
verification 

== Task 2 title

**Comment by camilamacedo86** [comment]
Hi @finp,

Is it something that still valid/required? If yes, please, could you try to do the first comment as [here](https://github.com/integr8ly/tutorial-web-app/blob/master/.github/ISSUE_TEMPLATE.md) and describe the steps required to reproduce and check this issue?  ( e.g #205 )

**Comment by finp** [comment]
moved to jira

**Comment by camilamacedo86** [comment]
What JIRA? Are not this team working just with the issues in the repo and trello for macro things?
