### ISSUE TITLE
resolve issues of resource content between walkthroughs 1x and 2

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#307]
## Description
@pb82  and @finp  have provided resource links in walthroughs, however there are a number of conflicts:

- order of services
- use of icons for services
- use of links and link titles

next steps:
- meet up and discuss best convention
- document conventions in style guide

**Comment by camilamacedo86** [comment]
Hi @finp,

Is it something that still valid/required? If yes, please, could you try to do the first comment as [here](https://github.com/integr8ly/tutorial-web-app/blob/master/.github/ISSUE_TEMPLATE.md) and describe the steps required to reproduce and check this issue?  ( e.g #205 )

**Comment by finp** [comment]
move to jira
