### ISSUE TITLE
URL length still too long in walkthrough 1 results in error in fuse 

### ISSUE THREAD

**Issue by maleck13** [integr8ly/tutorial-web-app#329]
## Description
A bug we resolved before has been reintroduced. For walkthrough 1 I ended up with a url for the frontend app that looked like 
http://crud-admin-example-com-1-integrating-event-and-api-driven-apps.apps.waterford-59b9.openshiftworkshop.com/v2/api-docs

Which is too long and is in an error state in OpenShift

## Expected Behaviour
A correct url be generated

## Steps to reproduce
Do walkthrough 1 from master 

Suggested Fix

The name of the route doesn't need to be unique across the cluster it only need to be unique to the ns. So you could call it "Frontend" and it would be fine

**Comment by maleck13** [comment]
@david-martin @pb82 FYI

**Comment by pb82** [comment]
Ok, we wanted more descriptive IDs for the walkthrough but i guess we should go back to 1,1A and 2 to shorten them.

**Comment by david-martin** [comment]
@pb82 I'd suggest we shorten the route name here rather than adjust the ids of the walkthroughs.
@maleck13 suggested a much simpler name as the Route name only needs to be unique in that namespace.
It's exteremely unlikely to clash given that its in a per-user per-walkthrough namespace

**Comment by maleck13** [comment]
Actually the route was also too long

**Comment by maleck13** [comment]
host name validation errors: spec.host: Invalid value:
            "frontend-admin-example-com-1-integrating-event-and-api-driven-apps.apps.waterford-59b9.openshiftworkshop.com":
            must be no more than 63 characters
