### ISSUE TITLE
Suggestion: parse git/folder walkthrough locations with the same logic

### ISSUE THREAD

**Issue by evanshortiss** [integr8ly/tutorial-web-app#347]
## Description
Apply the same logic to walkthrough imports regardless of source, i.e Git and folder locations should use the same logic. Matching the `path.join` from [line 175](https://github.com/integr8ly/tutorial-web-app/blob/master/server.js#L175) to [line 167](https://github.com/integr8ly/tutorial-web-app/blob/master/server.js#L167) would do the trick.

I say this is a "suggestion" since technically it's not a bug, but I spent a few minutes wondering why it failed since I assumed I was pointing to a top level location that the webapp would pull the `walkthroughs` directory from.

I'm using the following [file structure in the README](https://github.com/integr8ly/tutorial-web-app#131-layout-of-your-walkthroughs-directory), and followed this [example of setting the env var](https://github.com/integr8ly/tutorial-web-app#132-importing-your-external-walkthroughs-into-the-webapp) that doesn't include the `/walkthroughs` either.

## Expected Behavior
When using `WALKTHROUGH_LOCATIONS=/path/to/my-walkthroughs` or `WALKTHROUGH_LOCATIONS=https://github.com/integr8ly/tutorial-web-app-walkthroughs`I expect the web app to look for a nested `walkthroughs` folder. 

## Actual Behavior
When using `WALKTHROUGH_LOCATIONS=/path/to/my-walkthroughs` the `server.js` does not append the `/walkthroughs` so I get a blank webapp listing for walkthroughs unless I change to `WALKTHROUGH_LOCATIONS=/path/to/my-walkthroughs/walkthroughs`. 

## Environment
Local development using master and also tag 7d7df2045610 from quay.io

* Operating system: (macOS 10.14)
* Browser and version: (Chrome 70.0.3538.110)
* OpenShift version: n/a
* Node version: v8.12
* Npm version: 5.10
* Project Version/Tag: master commit 404333c and quay 7d7df2045610

## Steps to reproduce
You can recreate like so:

```
$ cd workspaces/integr8ly

$ git clone $WALKTHROUGHS_URL tutorial-web-app-walkthroughs

$ docker run -d -p 5001:5001 -e 'NODE_ENV=production' -e 'WALKTHROUGH_LOCATIONS=/opt/app-root/webapp-walkthroughs' -v /Users/$USERNAME/workspaces/integr8ly/tutorial-web-app-walkthroughs/:/opt/app-root/webapp-walkthroughs --name webapp quay.io/integreatly/tutorial-web-app
```

**Comment by tiffanynolan** [comment]
@evanshortiss Can this issue be closed?

**Comment by evanshortiss** [comment]
@tiffanynolan yep. Not super important.
