### ISSUE TITLE
Add ability to display images for ascii doc files.

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#41]
if you add images to the asciidoc, you cannot render them
eg added 
image:st0.png to introduction.adoc
replaced descriptionDoc reference in json 
doesn't render because app tries to render http://localhost:3006/tutorial/st0.png

Possible solution:
set imagesdir [1]
need to allow app to render files that aren't in 

[1] https://asciidoctor.org/docs/user-manual/

**Comment by finp** [comment]
ping @dlabaj @mfrances17

**Comment by dlabaj** [comment]
Current decision is to put files in public/images.

**Comment by finp** [comment]
fyi public/images works, but doesn't autosize the image as I'd expect.
hard-coding horizontal size to 800px for now

**Comment by dlabaj** [comment]
Thanks Paul.  I can look into 800px issue after we merge your pull request.

**Comment by mindreeper2420** [comment]
@dlabaj is there a way to add the class `img-responsive` to the images when published as html? That will automatically resize them and take care of the overflow.

**Comment by dlabaj** [comment]
@mfrances17 Do you know if we can do this if the image is in asciidocs?

**Comment by mindreeper2420** [comment]
@dlabaj I believe it would be something like this:

block image:

```
[.img-circle]
image::/images/someimage.gif[]
```

inline image:

```
image:/images/someimage.gif[role=img-circle]
```

**Comment by finp** [comment]
I was looking at some DIL walkthroughs and they have a lot of images,  
also, feedback suggests we need to add screenshots to existing walkthroughs.
Typically, CCS would use block images, syntax above looks good, we'd normally fill in some alt text:

`
[.img-responsive]
image::/images/someimage.gif[alt text]
`

**Comment by camilamacedo86** [comment]
Hi @finp,

Is it something that still valid/required? If yes, please, could you try to do the first comment as [here](https://github.com/integr8ly/tutorial-web-app/blob/master/.github/ISSUE_TEMPLATE.md) and describe the steps required to reproduce and check this issue?

**Comment by finp** [comment]
@pb82  I think this is solved by you recent work, can we close?

**Comment by pb82** [comment]
@finp it was @aidenkeating 's work, but yes i think this can be closed now.

**Comment by dlabaj** [comment]
Closed as this has been completed.
