### ISSUE TITLE
Update adoc files

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#5]
Make this the source of truth for adoc files. 
Migrate from finp/in8-docs master to **development** branch of this repo

fyi @priley86

**Comment by priley86** [comment]
sounds good @finp 👍

**Comment by stacymcauliffe** [comment]
@finp - I grabbed the text from your latest and made some review comments in a google doc. No show stoppers! Let me know if there is a better way to give you this kind of feedback. https://docs.google.com/document/d/1ns9B9uiz8ArgL7r8G7vMrkP_sJD8MGDbs9pukJa1UZw/edit?usp=sharing

**Comment by finp** [comment]
out of date, will follow up on gdoc
