### ISSUE TITLE
incorrect rendering of adoc headings

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#50]
when viewing http://localhost:3006/tutorial/0

if descriptionDoc starts with level 2 heading (==) the heading is rendered.
However if it starts with level 1(=) the heading isn't rendered

Is this by design, or an issue? @dlabaj

**Comment by dlabaj** [comment]
Looking into issue to see if it's something we need to support.

**Comment by finp** [comment]
I'm wondering if all headings are dropped somehow
ie each 'step' has a heading, but they don't seem to be rendered

**Comment by finp** [comment]
@dlabaj  what happened here?

**Comment by finp** [comment]
Note: this issue is resolved by PR #204

**Comment by david-martin** [comment]
closing in favour of resolution in #204
