### ISSUE TITLE
Thread id should be validated to only allow supported ids.

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#51]
<thread>.json uses an id to 'name' each walkthrough
We've now got a walkthrough 1A, and it seems to work as per #49 
However, I note that tutorial.js seems to test whether id is a number (for localization?), so am wondering if this is right approach?

**Comment by dlabaj** [comment]
Passing in 1A will work.   We should decide on what we want to allow for checks for an ID and only allow those.

**Comment by finp** [comment]
@dlabaj  closing - reopen if you see any value in it.
