### ISSUE TITLE
Valid GitHub repository URL fails validation in Application Settings

### ISSUE THREAD

**Issue by akieling** [integr8ly/tutorial-web-app#533]
## Description
In the Application settings page, entering a GitHub repository URL with host `github.com` fails validation.

## Expected Behavior
Validation shouldn't fail.

## Actual Behavior
Validation fails.

## Environment

Red Hat Solution Explorer
Integreatly Version: release-1.5.2
Console Version: 2.18.7
User Name: customer-admin
Browser Version: chrome 78.0.3904
Browser OS: Linux

## Steps to reproduce

1. Navigate to the Solution Explorer.
1. Click the gear icon in the top right to display the Application settings screen.
1. Enter the following URL: https://github.com/integr8ly/walkthrough-template.git

**Comment by evanshortiss** [comment]
@akieling try https://www.github.com/integr8ly/walkthrough-template.git as a workaround.

**Comment by akieling** [comment]
Yep. I did that. By the way, I'll try to fix it and send a PR, OK?

**Comment by mfrances17** [comment]
Do you mean it fails validation on the page? I fixed that issue a while back. And I just used that URL and it passes validation on the page and it shows up on the home screen.

**Comment by akieling** [comment]
The issue happens in the Integreatly Workshop available on RHPDS.

![tutorial-web-app-webapp apps abrianik-2e27 open redhat com_settings](https://user-images.githubusercontent.com/1910095/70649629-51848700-1c2c-11ea-9269-ad97bd5a2dab.png)

**Comment by akieling** [comment]
I've run `tutorial-web-app` locally and the issue seems to be fixed. Closing the issue.

**Comment by mfrances17** [comment]
Yeah, that's where mine is running, and I don't get the error since my fix... are you using an old version?

![no-www](https://user-images.githubusercontent.com/39063664/70649808-dd41e780-1c1b-11ea-8a58-77562880cb7b.png)

![result](https://user-images.githubusercontent.com/39063664/70649821-e03cd800-1c1b-11ea-864f-7a065f8de424.png)

**Comment by akieling** [comment]
Red Hat Solution Explorer
Integreatly Version: release-1.5.2
Console Version: 2.18.7
