### ISSUE TITLE
position and format of prereqs in walkthroughs

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#59]

**Comment by finp** [comment]
Currently, a URL like /tutorial/<id> 
- will display a Task 0 
- text is defined in json file
Proposal:
- move text to adoc
- remove task 0
Consequences:
- no interactivity 
- no time estimate given

However, on balance I think this is right move, to:
- avoid duplication with docs
- allow for editing by writer

**Comment by finp** [comment]
@dlabaj  This is where I suggest removing task 0 (ie prereqs)

**Comment by dlabaj** [comment]
@finp Is this still an issue?

**Comment by finp** [comment]
@dlabaj  AFAIK there is no task 0 in the current version of the app, so closing
