### ISSUE TITLE
need to do a hard refresh before you can see any SolX content

### ISSUE THREAD

**Issue by pwright** [integr8ly/tutorial-web-app#599]
`WALKTHROUGH_LOCATIONS=https://github.com/integr8ly/tutorial-web-app-walkthroughs yarn start:dev`

should 'just work', but it produces a blank screen

**Comment by hguerrero** [comment]
This problem shows up when using latest version from master. I works if I switch to tag `2.23.0`, however you still need to make a hard reload of the page.

**Comment by pwright** [comment]
I believe there are two issues, this one relates to the requirement for Ctrl-F5, and is not related to any version..
I don't have enough info to describe the @hguerrero  issue, but it went away by reverting to 2.23.0

**Comment by mfrances17** [comment]
This is a day 1 issue, when running locally you would always need to refresh the browser. Not saying it doesn't need to be fixed, but it's not something that was recently introduced.
