### ISSUE TITLE
task introductions are not being rendered

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#72]
Each task need some explanatory text,
It was hardcoded into json, but that was removed by this commit:
https://github.com/integr8ly/tutorial-web-app/commit/2f95ea71e5f6f7b632c54ed213896186b7f8d909#diff-8dbd8cb7c1f7b2cd546ce1238ee20d19

However, need to follow up with rendering *-introduction.adoc

**Comment by dlabaj** [comment]
Same bug as https://github.com/integr8ly/tutorial-web-app/issues/74

**Comment by dlabaj** [comment]
@finp Is this still an issue?

**Comment by finp** [comment]
my review of the latest mockups shows that these 'intros' have been removed from the design, closing
