### ISSUE TITLE
Add bash script to generate threads.json

### ISSUE THREAD

**Issue by dlabaj** [integr8ly/tutorial-web-app#80]
We need a bash script to generate threads.json from the ascii docs.

**Comment by dlabaj** [comment]
Need to see if this is relevant with changes to doc generation.

**Comment by tiffanynolan** [comment]
@dlabaj Does this still need to be worked on? If yes, can you create a task in JIRA and close this out?

**Comment by dlabaj** [comment]
Closing issue.  This is no longer relevant with the new implementation of the walkthroughs.
